// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ensemble_solution
Eigen::MatrixXd ensemble_solution(Eigen::MatrixXd par_diff, Eigen::MatrixXd obs_diff, Eigen::MatrixXd obs_resid, Eigen::MatrixXd par_resid, Eigen::VectorXd weights, Eigen::VectorXd parcov_inv, Eigen::MatrixXd Am, double cur_lam, double eigthresh, bool use_approx, bool use_prior_scaling, int iter, double reg_factor);
RcppExport SEXP _PESTO_ensemble_solution(SEXP par_diffSEXP, SEXP obs_diffSEXP, SEXP obs_residSEXP, SEXP par_residSEXP, SEXP weightsSEXP, SEXP parcov_invSEXP, SEXP AmSEXP, SEXP cur_lamSEXP, SEXP eigthreshSEXP, SEXP use_approxSEXP, SEXP use_prior_scalingSEXP, SEXP iterSEXP, SEXP reg_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type par_diff(par_diffSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type obs_diff(obs_diffSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type obs_resid(obs_residSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type par_resid(par_residSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type parcov_inv(parcov_invSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Am(AmSEXP);
    Rcpp::traits::input_parameter< double >::type cur_lam(cur_lamSEXP);
    Rcpp::traits::input_parameter< double >::type eigthresh(eigthreshSEXP);
    Rcpp::traits::input_parameter< bool >::type use_approx(use_approxSEXP);
    Rcpp::traits::input_parameter< bool >::type use_prior_scaling(use_prior_scalingSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< double >::type reg_factor(reg_factorSEXP);
    rcpp_result_gen = Rcpp::wrap(ensemble_solution(par_diff, obs_diff, obs_resid, par_resid, weights, parcov_inv, Am, cur_lam, eigthresh, use_approx, use_prior_scaling, iter, reg_factor));
    return rcpp_result_gen;
END_RCPP
}
// ensemble_solution_mda
Eigen::MatrixXd ensemble_solution_mda(Eigen::MatrixXd par_diff, Eigen::MatrixXd obs_diff, Eigen::MatrixXd obs_resid, Eigen::MatrixXd obs_err, double cur_lam, double eigthresh);
RcppExport SEXP _PESTO_ensemble_solution_mda(SEXP par_diffSEXP, SEXP obs_diffSEXP, SEXP obs_residSEXP, SEXP obs_errSEXP, SEXP cur_lamSEXP, SEXP eigthreshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type par_diff(par_diffSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type obs_diff(obs_diffSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type obs_resid(obs_residSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type obs_err(obs_errSEXP);
    Rcpp::traits::input_parameter< double >::type cur_lam(cur_lamSEXP);
    Rcpp::traits::input_parameter< double >::type eigthresh(eigthreshSEXP);
    rcpp_result_gen = Rcpp::wrap(ensemble_solution_mda(par_diff, obs_diff, obs_resid, obs_err, cur_lam, eigthresh));
    return rcpp_result_gen;
END_RCPP
}
// compute_phi
Eigen::VectorXd compute_phi(const Eigen::MatrixXd& residuals, const Eigen::VectorXd& weights);
RcppExport SEXP _PESTO_compute_phi(SEXP residualsSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type residuals(residualsSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_phi(residuals, weights));
    return rcpp_result_gen;
END_RCPP
}
// rsvd
Rcpp::List rsvd(const Eigen::MatrixXd& A, int k, int p, int q);
RcppExport SEXP _PESTO_rsvd(SEXP ASEXP, SEXP kSEXP, SEXP pSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(rsvd(A, k, p, q));
    return rcpp_result_gen;
END_RCPP
}
// accelerate_svd
Rcpp::List accelerate_svd(const Eigen::MatrixXd& A, bool thin);
RcppExport SEXP _PESTO_accelerate_svd(SEXP ASEXP, SEXP thinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type A(ASEXP);
    Rcpp::traits::input_parameter< bool >::type thin(thinSEXP);
    rcpp_result_gen = Rcpp::wrap(accelerate_svd(A, thin));
    return rcpp_result_gen;
END_RCPP
}
// adaptive_svd
Rcpp::List adaptive_svd(const Eigen::MatrixXd& A, int k, std::string method);
RcppExport SEXP _PESTO_adaptive_svd(SEXP ASEXP, SEXP kSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(adaptive_svd(A, k, method));
    return rcpp_result_gen;
END_RCPP
}
// ensemble_solution_gpu
Rcpp::List ensemble_solution_gpu(Eigen::MatrixXd par_diff, Eigen::MatrixXd obs_diff, Eigen::MatrixXd obs_resid, Eigen::MatrixXd par_resid, Eigen::VectorXd weights, Eigen::VectorXd parcov_inv, Eigen::MatrixXd Am, double cur_lam, double eigthresh, bool use_approx, bool use_prior_scaling, int iter, double reg_factor, std::string svd_method, int target_rank);
RcppExport SEXP _PESTO_ensemble_solution_gpu(SEXP par_diffSEXP, SEXP obs_diffSEXP, SEXP obs_residSEXP, SEXP par_residSEXP, SEXP weightsSEXP, SEXP parcov_invSEXP, SEXP AmSEXP, SEXP cur_lamSEXP, SEXP eigthreshSEXP, SEXP use_approxSEXP, SEXP use_prior_scalingSEXP, SEXP iterSEXP, SEXP reg_factorSEXP, SEXP svd_methodSEXP, SEXP target_rankSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type par_diff(par_diffSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type obs_diff(obs_diffSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type obs_resid(obs_residSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type par_resid(par_residSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type parcov_inv(parcov_invSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Am(AmSEXP);
    Rcpp::traits::input_parameter< double >::type cur_lam(cur_lamSEXP);
    Rcpp::traits::input_parameter< double >::type eigthresh(eigthreshSEXP);
    Rcpp::traits::input_parameter< bool >::type use_approx(use_approxSEXP);
    Rcpp::traits::input_parameter< bool >::type use_prior_scaling(use_prior_scalingSEXP);
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< double >::type reg_factor(reg_factorSEXP);
    Rcpp::traits::input_parameter< std::string >::type svd_method(svd_methodSEXP);
    Rcpp::traits::input_parameter< int >::type target_rank(target_rankSEXP);
    rcpp_result_gen = Rcpp::wrap(ensemble_solution_gpu(par_diff, obs_diff, obs_resid, par_resid, weights, parcov_inv, Am, cur_lam, eigthresh, use_approx, use_prior_scaling, iter, reg_factor, svd_method, target_rank));
    return rcpp_result_gen;
END_RCPP
}
// train_gp_surrogate
Rcpp::List train_gp_surrogate(const Eigen::MatrixXd& X_train, const Eigen::MatrixXd& Y_train, double length_scale, double signal_var, double noise_var);
RcppExport SEXP _PESTO_train_gp_surrogate(SEXP X_trainSEXP, SEXP Y_trainSEXP, SEXP length_scaleSEXP, SEXP signal_varSEXP, SEXP noise_varSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X_train(X_trainSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Y_train(Y_trainSEXP);
    Rcpp::traits::input_parameter< double >::type length_scale(length_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type signal_var(signal_varSEXP);
    Rcpp::traits::input_parameter< double >::type noise_var(noise_varSEXP);
    rcpp_result_gen = Rcpp::wrap(train_gp_surrogate(X_train, Y_train, length_scale, signal_var, noise_var));
    return rcpp_result_gen;
END_RCPP
}
// predict_gp_surrogate
Rcpp::List predict_gp_surrogate(const Rcpp::List& gp, const Eigen::MatrixXd& X_new);
RcppExport SEXP _PESTO_predict_gp_surrogate(SEXP gpSEXP, SEXP X_newSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type gp(gpSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X_new(X_newSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_gp_surrogate(gp, X_new));
    return rcpp_result_gen;
END_RCPP
}
// surrogate_ensemble_update
Rcpp::List surrogate_ensemble_update(const Eigen::MatrixXd& par_ensemble, const Eigen::MatrixXd& obs_ensemble, const Eigen::VectorXd& obs_target, const Eigen::VectorXd& weights, const Eigen::VectorXd& parcov_inv, double cur_lam, double uncertainty_threshold, double eigthresh);
RcppExport SEXP _PESTO_surrogate_ensemble_update(SEXP par_ensembleSEXP, SEXP obs_ensembleSEXP, SEXP obs_targetSEXP, SEXP weightsSEXP, SEXP parcov_invSEXP, SEXP cur_lamSEXP, SEXP uncertainty_thresholdSEXP, SEXP eigthreshSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type par_ensemble(par_ensembleSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type obs_ensemble(obs_ensembleSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type obs_target(obs_targetSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type parcov_inv(parcov_invSEXP);
    Rcpp::traits::input_parameter< double >::type cur_lam(cur_lamSEXP);
    Rcpp::traits::input_parameter< double >::type uncertainty_threshold(uncertainty_thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type eigthresh(eigthreshSEXP);
    rcpp_result_gen = Rcpp::wrap(surrogate_ensemble_update(par_ensemble, obs_ensemble, obs_target, weights, parcov_inv, cur_lam, uncertainty_threshold, eigthresh));
    return rcpp_result_gen;
END_RCPP
}
// adaptive_ensemble_size
Rcpp::List adaptive_ensemble_size(const Eigen::VectorXd& phi_values, int current_size, int min_size, int max_size, double cv_target);
RcppExport SEXP _PESTO_adaptive_ensemble_size(SEXP phi_valuesSEXP, SEXP current_sizeSEXP, SEXP min_sizeSEXP, SEXP max_sizeSEXP, SEXP cv_targetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type phi_values(phi_valuesSEXP);
    Rcpp::traits::input_parameter< int >::type current_size(current_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type min_size(min_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type max_size(max_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type cv_target(cv_targetSEXP);
    rcpp_result_gen = Rcpp::wrap(adaptive_ensemble_size(phi_values, current_size, min_size, max_size, cv_target));
    return rcpp_result_gen;
END_RCPP
}
// train_rff_surrogate
Rcpp::List train_rff_surrogate(const Eigen::MatrixXd& X_train, const Eigen::MatrixXd& Y_train, int n_features, double length_scale, double noise_var);
RcppExport SEXP _PESTO_train_rff_surrogate(SEXP X_trainSEXP, SEXP Y_trainSEXP, SEXP n_featuresSEXP, SEXP length_scaleSEXP, SEXP noise_varSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X_train(X_trainSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Y_train(Y_trainSEXP);
    Rcpp::traits::input_parameter< int >::type n_features(n_featuresSEXP);
    Rcpp::traits::input_parameter< double >::type length_scale(length_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type noise_var(noise_varSEXP);
    rcpp_result_gen = Rcpp::wrap(train_rff_surrogate(X_train, Y_train, n_features, length_scale, noise_var));
    return rcpp_result_gen;
END_RCPP
}
// predict_rff_surrogate
Rcpp::List predict_rff_surrogate(const Rcpp::List& rff, const Eigen::MatrixXd& X_new);
RcppExport SEXP _PESTO_predict_rff_surrogate(SEXP rffSEXP, SEXP X_newSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type rff(rffSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X_new(X_newSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_rff_surrogate(rff, X_new));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PESTO_ensemble_solution", (DL_FUNC) &_PESTO_ensemble_solution, 13},
    {"_PESTO_ensemble_solution_mda", (DL_FUNC) &_PESTO_ensemble_solution_mda, 6},
    {"_PESTO_compute_phi", (DL_FUNC) &_PESTO_compute_phi, 2},
    {"_PESTO_rsvd", (DL_FUNC) &_PESTO_rsvd, 4},
    {"_PESTO_accelerate_svd", (DL_FUNC) &_PESTO_accelerate_svd, 2},
    {"_PESTO_adaptive_svd", (DL_FUNC) &_PESTO_adaptive_svd, 3},
    {"_PESTO_ensemble_solution_gpu", (DL_FUNC) &_PESTO_ensemble_solution_gpu, 15},
    {"_PESTO_train_gp_surrogate", (DL_FUNC) &_PESTO_train_gp_surrogate, 5},
    {"_PESTO_predict_gp_surrogate", (DL_FUNC) &_PESTO_predict_gp_surrogate, 2},
    {"_PESTO_surrogate_ensemble_update", (DL_FUNC) &_PESTO_surrogate_ensemble_update, 8},
    {"_PESTO_adaptive_ensemble_size", (DL_FUNC) &_PESTO_adaptive_ensemble_size, 5},
    {"_PESTO_train_rff_surrogate", (DL_FUNC) &_PESTO_train_rff_surrogate, 5},
    {"_PESTO_predict_rff_surrogate", (DL_FUNC) &_PESTO_predict_rff_surrogate, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_PESTO(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
