# PESTO ensemble manifest — S7 class formalising the cross-package
# contract object that kernR, proxymix, and the paper skill consume.
# Year-1 §A5 of the UQ ag-stack roadmap.

#' PESTO Ensemble Manifest (S7 class)
#'
#' A versioned, hashed, provenance-tracked container for the result of a
#' PESTO ensemble run. The manifest is the cross-package contract object
#' that downstream consumers (`kernR`, `proxymix`, paper-skill) read; it
#' carries enough provenance to make a run independently reproducible and
#' independently verifiable (via [verify_manifest()]).
#'
#' Construct directly via the class constructor, or — preferred — via
#' [as_manifest()] applied to a `pesto_ies_callback_result`.
#'
#' @usage NULL
#'
#' @param schema_version Character. Semantic version of the manifest
#'   schema itself (default `"1.0.0"`).
#' @param run_id Character. Short identifier (auto-generated by
#'   [as_manifest()] if not supplied).
#' @param params `data.frame` / `data.table`. Parameter ensemble; first
#'   column `real_name`, subsequent columns one per parameter.
#' @param outputs `data.frame` / `data.table`. Simulated observation
#'   ensemble (same shape conventions as `params`).
#' @param weights Named numeric. IES observation weights (`1/obs_sd`).
#' @param obs_target Named numeric. Target observations.
#' @param seed Integer scalar. RNG seed used (`NA_integer_` if
#'   unrecorded).
#' @param data_hash Character. `sha256:...` checksum over
#'   `(params, outputs, weights, obs_target, seed)`.
#' @param fidelity Named numeric vector or `NULL`. Per-member fidelity
#'   tag for multi-fidelity runs.
#' @param apsim_version Character. APSIM version string
#'   (`NA_character_` when forward model is non-APSIM).
#' @param pesto_version Character. PESTO package version that produced
#'   the run.
#' @param timestamp `POSIXct`. Construction time.
#' @param method Character. One of `"ies_callback"`, `"ies_pst"`,
#'   `"mda"`, `"surrogate"`.
#' @param noptmax Integer. Number of IES iterations.
#' @param lambda_schedule Numeric vector. Marquardt lambdas per
#'   iteration.
#' @param failure_rate Numeric in `[0, 1]`. Fraction of forward
#'   evaluations that returned `NA`.
#'
#' @section Persistence:
#' See [write_manifest()] / [read_manifest()] for YAML serialisation
#' and [verify_manifest()] for integrity checking. The YAML file is the
#' authoritative human-readable entry; `params`, `outputs`, and the
#' assimilation context (`weights` + `obs_target`) are emitted as
#' sidecar files whose relative paths are recorded inside the YAML.
#' Three sidecar modes:
#'
#' * `format = "rds"` (default, **verifiable**) — RDS only. IEEE 754
#'   doubles round-trip bit-exactly; SHA-256 integrity check holds.
#' * `format = "both"` (**verifiable**) — RDS sidecars plus parallel
#'   `*_inspection.csv` files. Hash bound to RDS; CSVs are decorative.
#' * `format = "csv_unverified"` (**not verifiable**, renamed from
#'   `"csv"` in PESTO 0.3.2) — CSV-only sidecars. Hash is recorded
#'   but cannot be recomputed from disk (CSV formatter precision loss
#'   ~1 ULP). [verify_manifest()] returns `ok = NA + message`. Use
#'   only for one-way export to non-R analysts; round-trip integrity
#'   is by construction broken.
#'
#' The YAML carries an explicit `integrity:` field
#' (`"verifiable"` / `"not_verifiable"`) derived from `format` so
#' downstream non-R tools can branch on the integrity contract
#' without needing to know the kernR/PESTO-specific format
#' vocabulary.
#'
#' @examples
#' set.seed(1)
#' npar <- 2L; nobs <- 3L; nreal <- 30L
#' G <- matrix(stats::rnorm(nobs * npar), nobs, npar)
#' y <- as.numeric(G %*% c(0.5, -1.0)) + stats::rnorm(nobs, sd = 0.05)
#' names(y) <- paste0("o", seq_len(nobs))
#' prior <- matrix(stats::rnorm(nreal * npar), nreal, npar,
#'                 dimnames = list(NULL, c("a", "b")))
#' fit <- pesto_ies_callback(function(t) t %*% t(G), prior, y, 0.05,
#'                           noptmax = 3, verbose = FALSE)
#' m <- as_manifest(fit, seed = 1L)
#' verify_manifest(m)$ok
#' @export
pesto_ensemble_manifest <- S7::new_class(
  "pesto_ensemble_manifest",
  package = "PESTO",
  properties = list(
    schema_version  = S7::new_property(S7::class_character,
                                       default = "1.0.0"),
    run_id          = S7::class_character,
    params          = S7::class_data.frame,
    outputs         = S7::class_data.frame,
    weights         = S7::class_numeric,
    obs_target      = S7::class_numeric,
    seed            = S7::new_property(S7::class_integer,
                                       default = NA_integer_),
    data_hash       = S7::class_character,
    fidelity        = S7::new_property(S7::class_any, default = NULL),
    apsim_version   = S7::new_property(S7::class_character,
                                       default = NA_character_),
    pesto_version   = S7::class_character,
    timestamp       = S7::class_POSIXct,
    method          = S7::class_character,
    noptmax         = S7::class_integer,
    lambda_schedule = S7::class_numeric,
    failure_rate    = S7::new_property(S7::class_numeric, default = 0),
    format          = S7::new_property(S7::class_character,
                                       default = "rds")
  ),
  validator = function(self) {
    errs <- character(0)
    if (length(self@run_id) != 1L || !nzchar(self@run_id)) {
      errs <- c(errs, "`run_id` must be a single non-empty string")
    }
    if (nrow(self@params) != nrow(self@outputs)) {
      errs <- c(errs,
                "`params` and `outputs` must have equal row counts")
    }
    if (length(self@data_hash) != 1L) {
      errs <- c(errs, "`data_hash` must be a single string")
    }
    if (length(self@method) != 1L ||
        !self@method %in% c("ies_callback", "ies_pst", "mda", "surrogate")) {
      errs <- c(errs, paste0("`method` must be one of ies_callback, ",
                             "ies_pst, mda, surrogate"))
    }
    if (length(self@format) != 1L ||
        !self@format %in% c("rds", "both", "csv_unverified")) {
      errs <- c(errs,
                "`format` must be one of rds, both, csv_unverified")
    }
    if (length(errs) == 0L) NULL else paste(errs, collapse = "; ")
  }
)

#' Convert a PESTO ensemble result into a `pesto_ensemble_manifest`
#'
#' Wraps the plain-list result returned by [pesto_ies_callback()] (and,
#' eventually, [pesto_ies()]) in the S7 manifest contract object so
#' downstream packages can consume it via S7 dispatch without reaching
#' into PESTO-specific list internals.
#'
#' @param x A `pesto_ies_callback_result` (or any object with a method
#'   registered against this generic).
#' @param ... Method-specific arguments. For
#'   `pesto_ies_callback_result`: `run_id` (character, defaults to a
#'   timestamp+hash slug), `seed` (integer, defaults to `NA_integer_`),
#'   `fidelity` (named numeric or `NULL`), `apsim_version` (character,
#'   defaults to `NA_character_`).
#' @return A `pesto_ensemble_manifest` S7 object.
#' @export
as_manifest <- S7::new_generic("as_manifest", "x")

S7::method(as_manifest,
           S7::new_S3_class("pesto_ies_callback_result")) <-
  function(x, run_id = NULL, seed = NA_integer_,
           fidelity = NULL, apsim_version = NA_character_, ...) {
    .as_manifest_callback(x, run_id = run_id, seed = seed,
                          fidelity = fidelity,
                          apsim_version = apsim_version)
  }

#' Write a manifest to YAML + sidecar data files
#'
#' Serialises a `pesto_ensemble_manifest` as a YAML file at `file` plus
#' three data sidecars (`<basename>_params.<ext>`,
#' `<basename>_outputs.<ext>`, `<basename>_assim.<ext>`) in the same
#' directory. `<ext>` depends on `format`:
#'
#' * `"rds"` (default) — RDS sidecars only. IEEE 754 doubles round-trip
#'   bit-exactly; [verify_manifest()] recomputes the SHA-256 hash and
#'   confirms integrity.
#' * `"both"` — RDS sidecars **plus** parallel inspection CSVs
#'   (`<basename>_params_inspection.csv`, etc.). The hash is still
#'   bound to the RDS form; the CSVs are decorative only and are
#'   recorded in the YAML's `inspection_csv:` block.
#' * `"csv_unverified"` — CSV sidecars only. The hash is still recorded
#'   (computed from the in-memory binary representation) but
#'   [verify_manifest()] cannot recompute it from disk: CSV
#'   write-formatter precision loss (~1 ULP at IEEE 754 epsilon) would
#'   falsely fail the check. The YAML carries
#'   `integrity: not_verifiable` so downstream tools can branch
#'   accordingly. Renamed from `"csv"` in PESTO 0.3.2 (post critical
#'   review): the old name was indistinguishable at a glance from the
#'   verifiable modes, which the review judged a footgun. Old YAMLs
#'   with `format: csv` continue to read back correctly.
#'
#' @param manifest A `pesto_ensemble_manifest`.
#' @param ... Method-specific arguments. For
#'   `pesto_ensemble_manifest`: `file` (character path to the YAML
#'   output; parent directory must exist; sidecars are written next to
#'   it) and `format` (one of `"rds"`, `"both"`, `"csv_unverified"`).
#' @return Invisible character vector of the written paths (YAML +
#'   sidecars, in write order).
#' @export
write_manifest <- S7::new_generic("write_manifest", "manifest")

S7::method(write_manifest, pesto_ensemble_manifest) <-
  function(manifest, file,
           format = c("rds", "both", "csv_unverified")) {
    .assert_character_scalar(file, "file")
    # Accept the legacy 0.3.1 spelling for one minor cycle.
    if (length(format) == 1L && identical(format, "csv")) {
      warning(
        "write_manifest(format = \"csv\") is renamed to ",
        "\"csv_unverified\" in PESTO 0.3.2. The mode is unchanged ",
        "(CSV-only sidecars, hash not disk-verifiable). Update ",
        "call-sites to the new spelling.", call. = FALSE
      )
      format <- "csv_unverified"
    }
    format <- match.arg(format)
    dir <- dirname(file)
    if (!dir.exists(dir)) {
      stop(
        sprintf("Directory does not exist: %s", dir),
        call. = FALSE
      )
    }
    base <- tools::file_path_sans_ext(basename(file))

    params_df  <- as.data.frame(manifest@params)
    outputs_df <- as.data.frame(manifest@outputs)
    assim_df   <- data.frame(
      obs_name   = names(manifest@weights) %||%
                   paste0("o", seq_along(manifest@weights)),
      obs_target = as.numeric(manifest@obs_target),
      weight     = as.numeric(manifest@weights),
      stringsAsFactors = FALSE
    )

    written <- character(0)
    params_rds <- outputs_rds <- assim_rds <- NULL
    params_csv <- outputs_csv <- assim_csv <- NULL

    if (format %in% c("rds", "both")) {
      params_rds  <- file.path(dir, paste0(base, "_params.rds"))
      outputs_rds <- file.path(dir, paste0(base, "_outputs.rds"))
      assim_rds   <- file.path(dir, paste0(base, "_assim.rds"))
      saveRDS(params_df,  params_rds,  version = 3L)
      saveRDS(outputs_df, outputs_rds, version = 3L)
      saveRDS(assim_df,   assim_rds,   version = 3L)
      written <- c(written, params_rds, outputs_rds, assim_rds)
    }

    if (format %in% c("both", "csv_unverified")) {
      csv_suffix <- if (format == "both") "_inspection.csv" else ".csv"
      params_csv  <- file.path(dir, paste0(base, "_params",  csv_suffix))
      outputs_csv <- file.path(dir, paste0(base, "_outputs", csv_suffix))
      assim_csv   <- file.path(dir, paste0(base, "_assim",   csv_suffix))
      utils::write.csv(params_df,  params_csv,  row.names = FALSE)
      utils::write.csv(outputs_df, outputs_csv, row.names = FALSE)
      utils::write.csv(assim_df,   assim_csv,   row.names = FALSE)
      written <- c(written, params_csv, outputs_csv, assim_csv)
    }

    # Stamp the manifest's format slot so the YAML reflects how the
    # bytes on disk were written (the slot on the in-memory object is
    # left unchanged for caller-side inspection).
    manifest_for_yaml <- manifest
    manifest_for_yaml@format <- format

    yaml_list <- .manifest_to_yaml_list(
      manifest_for_yaml,
      params_path  = if (!is.null(params_rds))  basename(params_rds)
                     else basename(params_csv),
      outputs_path = if (!is.null(outputs_rds)) basename(outputs_rds)
                     else basename(outputs_csv),
      assim_path   = if (!is.null(assim_rds))   basename(assim_rds)
                     else basename(assim_csv),
      inspection_csv = if (format == "both") {
        list(params  = basename(params_csv),
             outputs = basename(outputs_csv),
             assim   = basename(assim_csv))
      } else NULL
    )
    yaml::write_yaml(yaml_list, file)

    invisible(c(file, written))
  }

#' Read a manifest from YAML + sidecar data files
#'
#' Inverse of [write_manifest()]. Reads the YAML, loads the three
#' sidecar data files (paths resolved relative to the YAML file), and
#' reconstructs the `pesto_ensemble_manifest` S7 object. The file
#' extensions in the YAML's `artefacts:` block determine the read path
#' (`.rds` via `readRDS`, `.csv` via `utils::read.csv`).
#'
#' @param file Character. Path to the YAML manifest file.
#' @return A `pesto_ensemble_manifest`.
#' @export
read_manifest <- function(file) {
  .assert_path_exists(file, "file")
  yaml_list <- yaml::read_yaml(file)
  dir <- dirname(normalizePath(file))
  read_one <- function(rel_path) {
    full <- file.path(dir, rel_path)
    ext  <- tolower(tools::file_ext(rel_path))
    if (ext == "rds") {
      readRDS(full)
    } else if (ext == "csv") {
      utils::read.csv(full, stringsAsFactors = FALSE,
                      check.names = FALSE)
    } else {
      stop(
        sprintf(
          "Unsupported sidecar extension '.%s' in manifest YAML.", ext
        ),
        call. = FALSE
      )
    }
  }
  params  <- read_one(yaml_list$artefacts$params)
  outputs <- read_one(yaml_list$artefacts$outputs)
  assim   <- read_one(yaml_list$artefacts$assim)
  .yaml_list_to_manifest(yaml_list, params = params,
                         outputs = outputs, assim = assim)
}

#' Verify the integrity of a manifest
#'
#' Recomputes the SHA-256 hash over `(params, outputs, weights,
#' obs_target, seed)` and compares against the stored `data_hash`. Use
#' this after [read_manifest()] to confirm the data files have not been
#' tampered with or silently re-saved.
#'
#' When the manifest's `format` slot is `"csv"`, the on-disk data has
#' been round-tripped through `utils::read.csv()` and IEEE 754 doubles
#' have been truncated at the formatter's precision (~15-17 digits).
#' That precision loss is enough to flip the SHA-256 hash, so
#' `verify_manifest()` returns `ok = NA` with an explanatory
#' `message` field rather than reporting a spurious `FALSE`.
#'
#' @param manifest A `pesto_ensemble_manifest`.
#' @param ... Reserved.
#' @return A list with `ok` (`TRUE`, `FALSE`, or `NA` — see Details),
#'   `stored` (the manifest's recorded hash), `recomputed` (the hash
#'   computed from current data), and `message` (`NULL` for verifiable
#'   formats, otherwise an explanation).
#' @export
verify_manifest <- S7::new_generic("verify_manifest", "manifest")

S7::method(verify_manifest, pesto_ensemble_manifest) <-
  function(manifest, ...) {
    recomputed <- paste0("sha256:", .compute_data_hash_inputs(
      params      = manifest@params,
      outputs     = manifest@outputs,
      weights     = manifest@weights,
      obs_target  = manifest@obs_target,
      seed        = manifest@seed
    ))
    if (identical(manifest@format, "csv_unverified") ||
        identical(manifest@format, "csv")) {
      return(list(
        ok         = NA,
        stored     = manifest@data_hash,
        recomputed = recomputed,
        message    = paste0(
          "manifest format is '", manifest@format,
          "' (integrity: not_verifiable); bit-exact hash ",
          "verification is not possible from CSV sidecars ",
          "(formatter precision loss). Re-write with ",
          "format = 'rds' or 'both' for verifiable integrity."
        )
      ))
    }
    list(
      ok         = identical(recomputed, manifest@data_hash),
      stored     = manifest@data_hash,
      recomputed = recomputed,
      message    = NULL
    )
  }

# Pretty-printer. S7 dispatch on base R's `print` generic — registered
# via the S7 method table so the S7 object's default printer (which
# would dump all slot values verbatim) is overridden.
S7::method(print, pesto_ensemble_manifest) <- function(x, ...) {
  cat("<pesto_ensemble_manifest> schema ", x@schema_version, "\n", sep = "")
  cat("  run_id        : ", x@run_id, "\n", sep = "")
  cat("  method        : ", x@method,
      "  (noptmax=", x@noptmax, ")\n", sep = "")
  cat("  ensemble      : ", nrow(x@params), " realisations x ",
      ncol(x@params) - 1L, " parameters | ",
      ncol(x@outputs) - 1L, " observations\n", sep = "")
  cat("  failure rate  : ",
      sprintf("%.2f%%", 100 * x@failure_rate), "\n", sep = "")
  cat("  pesto version : ", x@pesto_version,
      "  apsim: ", as.character(x@apsim_version), "\n", sep = "")
  cat("  timestamp     : ",
      format(x@timestamp, "%Y-%m-%dT%H:%M:%S%z"), "\n", sep = "")
  cat("  data hash     : ", x@data_hash, "\n", sep = "")
  invisible(x)
}

# ---- internals ---------------------------------------------------------

.as_manifest_callback <- function(x, run_id = NULL,
                                  seed = NA_integer_,
                                  fidelity = NULL,
                                  apsim_version = NA_character_) {

  if (is.null(x$weights)) {
    stop(
      paste0(
        "Callback result is missing the `weights` slot. ",
        "Rerun under PESTO >= 0.2.0."
      ),
      call. = FALSE
    )
  }
  if (is.null(x$obs_target)) {
    stop(
      paste0(
        "Callback result is missing the `obs_target` slot. ",
        "Rerun under PESTO >= 0.2.0."
      ),
      call. = FALSE
    )
  }
  weights_vec    <- x$weights
  obs_target_vec <- x$obs_target

  lambdas <- vapply(
    x$iterations,
    function(it) if (is.null(it$lambda)) NA_real_ else it$lambda,
    numeric(1L)
  )

  if (is.null(run_id)) {
    run_id <- sprintf(
      "ies_callback_%s_%s",
      format(Sys.time(), "%Y%m%d_%H%M%S"),
      substr(digest::digest(x, algo = "xxhash32"), 1L, 8L)
    )
  }

  hash <- paste0("sha256:", .compute_data_hash_inputs(
    params     = x$par_ensemble,
    outputs    = x$obs_ensemble,
    weights    = weights_vec,
    obs_target = obs_target_vec,
    seed       = as.integer(seed)
  ))

  pesto_ensemble_manifest(
    run_id          = run_id,
    params          = as.data.frame(x$par_ensemble),
    outputs         = as.data.frame(x$obs_ensemble),
    weights         = weights_vec,
    obs_target      = obs_target_vec,
    seed            = as.integer(seed),
    data_hash       = hash,
    fidelity        = fidelity,
    apsim_version   = as.character(apsim_version),
    pesto_version   = as.character(utils::packageVersion("PESTO")),
    timestamp       = Sys.time(),
    method          = "ies_callback",
    noptmax         = length(x$iterations),
    lambda_schedule = lambdas,
    failure_rate    = if (is.null(x$failure_rate)) 0 else x$failure_rate
  )
}

# Canonicalise inputs before hashing so trivially different
# representations (data.frame vs data.table, attribute drift, name
# ordering on the weights vector) do not produce different hashes.
.compute_data_hash_inputs <- function(params, outputs, weights,
                                      obs_target, seed) {
  digest::digest(
    list(
      params     = as.matrix(as.data.frame(params)[
        , setdiff(names(params), "real_name"), drop = FALSE]),
      outputs    = as.matrix(as.data.frame(outputs)[
        , setdiff(names(outputs), "real_name"), drop = FALSE]),
      weights    = as.numeric(weights),
      obs_target = as.numeric(obs_target),
      seed       = as.integer(seed)
    ),
    algo      = "sha256",
    serialize = TRUE
  )
}

.manifest_to_yaml_list <- function(m, params_path, outputs_path,
                                   assim_path, inspection_csv = NULL) {
  # `integrity` is derived from `format`. Persisting it on the
  # serialised side lets non-R consumers (Python tooling, paper-skill
  # graders) branch on the integrity contract without parsing the
  # PESTO-specific format vocabulary.
  integrity <- if (m@format %in% c("rds", "both")) "verifiable"
               else                                "not_verifiable"
  out <- list(
    schema_version  = m@schema_version,
    run_id          = m@run_id,
    data_hash       = m@data_hash,
    format          = m@format,
    integrity       = integrity,
    artefacts       = list(
      params  = params_path,
      outputs = outputs_path,
      assim   = assim_path
    ),
    seed            = if (is.na(m@seed)) NULL else as.integer(m@seed),
    fidelity        = if (is.null(m@fidelity)) NULL else as.list(m@fidelity),
    apsim_version   = if (is.na(m@apsim_version)) NULL
                      else as.character(m@apsim_version),
    pesto_version   = m@pesto_version,
    timestamp       = format(m@timestamp, "%Y-%m-%dT%H:%M:%S%z"),
    context         = list(
      method          = m@method,
      noptmax         = m@noptmax,
      lambda_schedule = as.numeric(m@lambda_schedule),
      failure_rate    = m@failure_rate
    )
  )
  if (!is.null(inspection_csv)) {
    out$inspection_csv <- inspection_csv
  }
  out
}

.yaml_list_to_manifest <- function(yl, params, outputs, assim) {
  ctx <- yl$context %||% list()
  weights_vec    <- stats::setNames(as.numeric(assim$weight),
                                    as.character(assim$obs_name))
  obs_target_vec <- stats::setNames(as.numeric(assim$obs_target),
                                    as.character(assim$obs_name))
  pesto_ensemble_manifest(
    schema_version  = yl$schema_version %||% "1.0.0",
    run_id          = yl$run_id,
    params          = as.data.frame(params),
    outputs         = as.data.frame(outputs),
    weights         = weights_vec,
    obs_target      = obs_target_vec,
    seed            = if (is.null(yl$seed)) NA_integer_
                      else as.integer(yl$seed),
    data_hash       = yl$data_hash,
    fidelity        = if (is.null(yl$fidelity)) NULL
                      else as.numeric(unlist(yl$fidelity)),
    apsim_version   = if (is.null(yl$apsim_version)) NA_character_
                      else as.character(yl$apsim_version),
    pesto_version   = as.character(yl$pesto_version),
    timestamp       = as.POSIXct(yl$timestamp,
                                 format = "%Y-%m-%dT%H:%M:%S%z",
                                 tz = "UTC"),
    method          = ctx$method   %||% "ies_callback",
    noptmax         = as.integer(ctx$noptmax %||% 0L),
    lambda_schedule = as.numeric(ctx$lambda_schedule %||% numeric(0)),
    failure_rate    = as.numeric(ctx$failure_rate %||% 0),
    format          = {
      f <- yl$format %||% "rds"
      # Normalise the 0.3.1 spelling on read so existing manifests
      # round-trip cleanly through the renamed vocabulary.
      if (identical(f, "csv")) "csv_unverified" else f
    }
  )
}

# Local `%||%`. The same helper lives in apsim_callback.R; both are
# package-internal, so the duplication has no namespace cost.
`%||%` <- function(x, y) if (is.null(x)) y else x
