# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Ensemble Solution Kernel (GLM form)
#'
#' Implements the core IES ensemble update equation using the
#' Gauss-Levenberg-Marquardt (GLM) formulation from Chen & Oliver (2013).
#' This is the computational hotspot of the iterative ensemble smoother.
#'
#' The update equation solves:
#' \deqn{\Delta\theta = -\Delta\theta' V s (s^2 + \lambda I)^{-1} U^T r}
#' where the SVD is performed on the scaled observation difference matrix.
#'
#' @param par_diff Matrix (npar x nreal). Parameter anomalies (deviations from mean).
#' @param obs_diff Matrix (nobs x nreal). Observation anomalies.
#' @param obs_resid Matrix (nobs x nreal). Observation residuals,
#'   simulated minus observed (sim - obs). This sign convention is required so
#'   that the leading negative in the GLM update
#'   (\eqn{\Delta\theta = -\Delta\theta' V s (s^2 + \lambda I)^{-1} U^T r})
#'   yields a descent step on \eqn{\Phi = \|W(g(\theta) - d^{obs})\|^2}.
#'   Passing (obs - sim) inverts the gradient and causes phi to diverge.
#' @param par_resid Matrix (npar x nreal). Parameter residuals (par - prior mean).
#' @param weights Numeric vector (nobs). Observation weights (1/sqrt(variance)).
#' @param parcov_inv Numeric vector (npar). Diagonal of inverse parameter covariance.
#' @param Am Matrix (npar x nreal-1). Random Am matrix for upgrade_2 (optional).
#' @param cur_lam Numeric. Current Marquardt lambda.
#' @param eigthresh Numeric. Eigenvalue truncation threshold (0-1).
#' @param use_approx Logical. If TRUE, skip upgrade_2 (prior-scaling correction).
#' @param use_prior_scaling Logical. Scale by prior covariance.
#' @param iter Integer. Current iteration number.
#' @param reg_factor Numeric. Regularisation factor for upgrade_2 blending.
#' @return Matrix (nreal x npar). Parameter upgrade vectors (one row per realisation).
#'   The returned matrix is the *negative-direction* step from the Chen-Oliver
#'   2013 GLM update formula. To advance the ensemble, apply by subtraction:
#'   `par_new = par_old - upgrade`. The R-side driver
#'   [pesto_ies_callback()] handles this convention internally.
#' @examples
#' set.seed(1L)
#' npar  <- 4L
#' nreal <- 20L
#' nobs  <- 30L
#' par_diff  <- matrix(rnorm(npar * nreal), npar, nreal)
#' obs_diff  <- matrix(rnorm(nobs * nreal), nobs, nreal)
#' obs_resid <- matrix(rnorm(nobs * nreal, sd = 0.5), nobs, nreal)
#' par_resid <- matrix(rnorm(npar * nreal, sd = 0.1), npar, nreal)
#' weights    <- rep(1, nobs)
#' parcov_inv <- rep(1, npar)
#' Am         <- matrix(0, 0, 0)
#' upgrade <- ensemble_solution(
#'   par_diff   = par_diff,
#'   obs_diff   = obs_diff,
#'   obs_resid  = obs_resid,
#'   par_resid  = par_resid,
#'   weights    = weights,
#'   parcov_inv = parcov_inv,
#'   Am         = Am,
#'   cur_lam    = 1.0
#' )
#' dim(upgrade)
#' @export
ensemble_solution <- function(par_diff, obs_diff, obs_resid, par_resid, weights, parcov_inv, Am, cur_lam, eigthresh = 1e-6, use_approx = TRUE, use_prior_scaling = FALSE, iter = 1L, reg_factor = -1.0) {
    .Call(`_PESTO_ensemble_solution`, par_diff, obs_diff, obs_resid, par_resid, weights, parcov_inv, Am, cur_lam, eigthresh, use_approx, use_prior_scaling, iter, reg_factor)
}

#' Ensemble Solution Kernel (MDA / Evensen form)
#'
#' Implements the Multiple Data Assimilation (MDA) update from
#' Evensen (2018), Section 14.3.2. Uses low-rank representation
#' of the error covariance.
#'
#' @param par_diff Matrix (npar x nreal). Parameter anomalies.
#' @param obs_diff Matrix (nobs x nreal). Observation anomalies.
#' @param obs_resid Matrix (nobs x nreal). Observation residuals.
#' @param obs_err Matrix (nobs x nreal). Observation error realisations.
#' @param cur_lam Numeric. Inflation factor.
#' @param eigthresh Numeric. Eigenvalue truncation threshold.
#' @return Matrix (nreal x npar). Parameter upgrade vectors.
#' @examples
#' set.seed(1L)
#' npar  <- 4L
#' nreal <- 20L
#' nobs  <- 30L
#' par_diff  <- matrix(rnorm(npar * nreal), npar, nreal)
#' obs_diff  <- matrix(rnorm(nobs * nreal), nobs, nreal)
#' obs_resid <- matrix(rnorm(nobs * nreal, sd = 0.5), nobs, nreal)
#' obs_err   <- matrix(rnorm(nobs * nreal, sd = 0.5), nobs, nreal)
#' upgrade <- ensemble_solution_mda(
#'   par_diff  = par_diff,
#'   obs_diff  = obs_diff,
#'   obs_resid = obs_resid,
#'   obs_err   = obs_err,
#'   cur_lam   = 1.0
#' )
#' dim(upgrade)
#' @export
ensemble_solution_mda <- function(par_diff, obs_diff, obs_resid, obs_err, cur_lam = 1.0, eigthresh = 1e-6) {
    .Call(`_PESTO_ensemble_solution_mda`, par_diff, obs_diff, obs_resid, obs_err, cur_lam, eigthresh)
}

#' Compute Phi (Objective Function) for Ensemble
#'
#' Calculates the weighted sum of squared residuals for each
#' realisation in the ensemble.
#'
#' @param residuals Matrix (nobs x nreal). Observation residuals.
#' @param weights Numeric vector (nobs). Observation weights.
#' @return Numeric vector (nreal). Phi value per realisation.
#' @examples
#' set.seed(1L)
#' residuals <- matrix(rnorm(5 * 4), 5, 4)
#' weights   <- rep(1, 5)
#' phi <- compute_phi(residuals, weights)
#' length(phi)
#' phi
#' @export
compute_phi <- function(residuals, weights) {
    .Call(`_PESTO_compute_phi`, residuals, weights)
}

#' Randomised SVD (Halko-Martinsson-Tropp Algorithm)
#'
#' Computes a rank-k approximation to the SVD using randomised
#' projections. This is asymptotically faster than full SVD for
#' problems where the target rank k is much smaller than min(m,n).
#'
#' Complexity: O(mn*k) vs O(mn*min(m,n)) for full SVD.
#'
#' @param A Matrix (m x n). Input matrix.
#' @param k Integer. Target rank (number of singular values to compute).
#' @param p Integer. Oversampling parameter (default 10). Higher = more accurate.
#' @param q Integer. Number of power iterations (default 2). Higher = better for
#'   matrices with slowly decaying singular values.
#' @return A list with components U (m x k), d (k), V (n x k).
#' @references
#' Halko, N., Martinsson, P.G., & Tropp, J.A. (2011). Finding structure
#' with randomness: Probabilistic algorithms for constructing approximate
#' matrix decompositions. SIAM Review, 53(2), 217-288.
#' @examples
#' set.seed(1L)
#' A <- matrix(rnorm(10 * 6), nrow = 10, ncol = 6)
#' res <- rsvd(A, k = 3L)
#' length(res$d)
#' A_hat <- res$u %*% diag(res$d) %*% t(res$v)
#' mean((A - A_hat)^2)
#' @export
rsvd <- function(A, k, p = 10L, q = 2L) {
    .Call(`_PESTO_rsvd`, A, k, p, q)
}

#' Hardware-Accelerated SVD via LAPACK
#'
#' Uses R's linked LAPACK (which on macOS is Apple Accelerate/AMX,
#' on Linux is typically OpenBLAS or MKL) for hardware-optimised
#' SVD computation.
#'
#' @param A Matrix (m x n). Input matrix.
#' @param thin Logical. If TRUE (default), compute thin SVD.
#' @return A list with components U, d, V.
#' @examples
#' set.seed(1L)
#' A <- matrix(rnorm(8 * 5), nrow = 8, ncol = 5)
#' res <- accelerate_svd(A, thin = TRUE)
#' length(res$d)
#' all.equal(sort(res$d, decreasing = TRUE), svd(A)$d)
#' @export
accelerate_svd <- function(A, thin = TRUE) {
    .Call(`_PESTO_accelerate_svd`, A, thin)
}

#' Adaptive SVD with Automatic Backend Selection
#'
#' Automatically selects the optimal SVD algorithm based on matrix
#' dimensions and available hardware:
#'
#' - **Randomised SVD** (Halko et al., 2011): when target rank k << min(m,n)
#' - **Apple Accelerate**: on macOS, for full SVD leveraging AMX coprocessor
#' - **Eigen BDCSVD**: cross-platform fallback with divide-and-conquer
#' - **CUDA cuSOLVER**: on GPU-equipped systems (when compiled with PESTO_USE_CUDA)
#'
#' @param A Matrix (m x n). Input matrix.
#' @param k Integer. Target rank. If 0 (default), computes full SVD.
#' @param method Character. Force a specific method: "auto" (default),
#'   "rsvd", "accelerate", "eigen", "cuda".
#' @return A list with components U (m x k), d (k), V (n x k),
#'   plus `method_used` and `time_ms`.
#' @examples
#' set.seed(1L)
#' A <- matrix(rnorm(20 * 12), nrow = 20, ncol = 12)
#' res <- adaptive_svd(A, k = 5L, method = "auto")
#' length(res$d)
#' is.character(res$method_used)
#' @export
adaptive_svd <- function(A, k = 0L, method = "auto") {
    .Call(`_PESTO_adaptive_svd`, A, k, method)
}

#' Ensemble Solution with Adaptive SVD Backend
#'
#' Enhanced version of `ensemble_solution()` that uses the adaptive SVD
#' backend for automatic hardware acceleration. On macOS, uses Apple
#' Accelerate (AMX coprocessor). On CUDA systems, uses cuSOLVER.
#' For low-rank problems, automatically switches to randomised SVD.
#'
#' @param par_diff Matrix (npar x nreal). Parameter anomalies.
#' @param obs_diff Matrix (nobs x nreal). Observation anomalies.
#' @param obs_resid Matrix (nobs x nreal). Observation residuals.
#' @param par_resid Matrix (npar x nreal). Parameter residuals.
#' @param weights Numeric vector (nobs). Observation weights.
#' @param parcov_inv Numeric vector (npar). Inverse parameter covariance diagonal.
#' @param Am Matrix. Random Am matrix for upgrade_2.
#' @param cur_lam Numeric. Marquardt lambda.
#' @param eigthresh Numeric. Eigenvalue truncation threshold.
#' @param use_approx Logical. Skip upgrade_2.
#' @param use_prior_scaling Logical. Scale by prior covariance.
#' @param iter Integer. Current iteration.
#' @param reg_factor Numeric. Regularisation factor.
#' @param svd_method Character. SVD method: "auto", "rsvd", "accelerate", "eigen".
#' @param target_rank Integer. Target rank for randomised SVD (0 = auto).
#' @return A list with upgrade matrix and performance diagnostics.
#' @examples
#' set.seed(1L)
#' npar  <- 4L
#' nreal <- 20L
#' nobs  <- 30L
#' par_diff  <- matrix(rnorm(npar * nreal), npar, nreal)
#' obs_diff  <- matrix(rnorm(nobs * nreal), nobs, nreal)
#' obs_resid <- matrix(rnorm(nobs * nreal, sd = 0.5), nobs, nreal)
#' par_resid <- matrix(rnorm(npar * nreal, sd = 0.1), npar, nreal)
#' weights    <- rep(1, nobs)
#' parcov_inv <- rep(1, npar)
#' Am         <- matrix(0, 0, 0)
#' res <- ensemble_solution_gpu(
#'   par_diff   = par_diff,
#'   obs_diff   = obs_diff,
#'   obs_resid  = obs_resid,
#'   par_resid  = par_resid,
#'   weights    = weights,
#'   parcov_inv = parcov_inv,
#'   Am         = Am,
#'   cur_lam    = 1.0,
#'   svd_method = "auto"
#' )
#' dim(res$upgrade)
#' @export
ensemble_solution_gpu <- function(par_diff, obs_diff, obs_resid, par_resid, weights, parcov_inv, Am, cur_lam, eigthresh = 1e-6, use_approx = TRUE, use_prior_scaling = FALSE, iter = 1L, reg_factor = -1.0, svd_method = "auto", target_rank = 0L) {
    .Call(`_PESTO_ensemble_solution_gpu`, par_diff, obs_diff, obs_resid, par_resid, weights, parcov_inv, Am, cur_lam, eigthresh, use_approx, use_prior_scaling, iter, reg_factor, svd_method, target_rank)
}

#' Train a Gaussian Process Surrogate
#'
#' Trains a GP surrogate model from parameter-observation pairs.
#' Uses squared exponential (RBF) kernel with automatic relevance
#' determination (ARD) via median heuristic for length scale.
#'
#' The GP learns the mapping: parameters -> observations, enabling
#' cheap prediction of model outputs for new parameter sets.
#'
#' @param X_train Matrix (n x npar). Training parameter sets.
#' @param Y_train Matrix (n x nobs). Corresponding model outputs.
#' @param length_scale Numeric. Kernel length scale. If 0 (default),
#'   uses the median heuristic (median pairwise distance).
#' @param signal_var Numeric. Signal variance. If 0, uses variance of Y.
#' @param noise_var Numeric. Observation noise variance.
#' @return A list of class `step_gp` containing trained GP components:
#'   K_inv (inverse kernel matrix), alpha (weight vectors), hyperparameters.
#' @examples
#' set.seed(1L)
#' X_train <- matrix(rnorm(20 * 4), 20, 4)
#' Y_train <- matrix(rnorm(20 * 6), 20, 6)
#' gp <- train_gp_surrogate(X_train, Y_train)
#' pred <- predict_gp_surrogate(gp, X_train)
#' dim(pred$mean)
#' length(pred$uncertainty)
#' @export
train_gp_surrogate <- function(X_train, Y_train, length_scale = 0.0, signal_var = 0.0, noise_var = 1e-4) {
    .Call(`_PESTO_train_gp_surrogate`, X_train, Y_train, length_scale, signal_var, noise_var)
}

#' Predict with GP Surrogate (with Uncertainty)
#'
#' Generates predictions and prediction uncertainties for new parameter
#' sets using a trained GP surrogate. The uncertainty estimates are
#' crucial for the adaptive switching criterion.
#'
#' @param gp A trained GP model (from `train_gp_surrogate`).
#' @param X_new Matrix (m x npar). New parameter sets to predict.
#' @return A list with:
#'   \describe{
#'     \item{mean}{Matrix (m x nobs). Predicted observations.}
#'     \item{variance}{Matrix (m x nobs). Prediction variance per output.}
#'     \item{uncertainty}{Numeric vector (m). Mean prediction uncertainty per realisation.}
#'   }
#' @examples
#' set.seed(1L)
#' X_train <- matrix(rnorm(20 * 4), 20, 4)
#' Y_train <- matrix(rnorm(20 * 6), 20, 6)
#' gp      <- train_gp_surrogate(X_train, Y_train)
#' X_new   <- matrix(rnorm(5 * 4), 5, 4)
#' pred    <- predict_gp_surrogate(gp, X_new)
#' dim(pred$mean)
#' length(pred$uncertainty)
#' @export
predict_gp_surrogate <- function(gp, X_new) {
    .Call(`_PESTO_predict_gp_surrogate`, gp, X_new)
}

#' Surrogate-Accelerated Ensemble Update
#'
#' Performs an IES update step using a GP surrogate for cheap
#' pre-screening, with adaptive switching to the full model
#' based on prediction uncertainty.
#'
#' **Algorithm:**
#' 1. Train GP surrogate from current ensemble evaluations
#' 2. Generate candidate upgrades using surrogate predictions
#' 3. Evaluate uncertainty of surrogate predictions
#' 4. Run full model only for realisations where uncertainty exceeds threshold
#' 5. Blend surrogate and model results using control-variate correction
#'
#' This typically reduces full model evaluations by 50-90%.
#'
#' @param par_ensemble Matrix (nreal x npar). Current parameter ensemble.
#' @param obs_ensemble Matrix (nreal x nobs). Current observation ensemble (from model).
#' @param obs_target Numeric vector (nobs). Target observations.
#' @param weights Numeric vector (nobs). Observation weights.
#' @param parcov_inv Numeric vector (npar). Inverse parameter covariance diagonal.
#' @param cur_lam Numeric. Marquardt lambda.
#' @param uncertainty_threshold Numeric. Threshold for surrogate/model switching.
#'   Realisations with GP uncertainty above this are re-evaluated with full model.
#'   Default 0.1 (10% of signal variance).
#' @param eigthresh Numeric. SVD eigenvalue threshold.
#' @return A list with:
#'   \describe{
#'     \item{upgrade}{Matrix. Parameter upgrades.}
#'     \item{n_model_runs}{Integer. Number of full model evaluations needed.}
#'     \item{n_surrogate_runs}{Integer. Number of surrogate evaluations.}
#'     \item{savings_pct}{Numeric. Percentage of model runs saved.}
#'     \item{gp_diagnostics}{List. GP training diagnostics.}
#'   }
#' @examples
#' \donttest{
#' set.seed(1L)
#' npar  <- 5L
#' nreal <- 15L
#' nobs  <- 8L
#' par_ensemble <- matrix(rnorm(nreal * npar), nreal, npar)
#' obs_ensemble <- matrix(rnorm(nreal * nobs), nreal, nobs)
#' obs_target   <- rnorm(nobs)
#' weights      <- rep(1, nobs)
#' parcov_inv   <- rep(1, npar)
#' res <- surrogate_ensemble_update(
#'   par_ensemble = par_ensemble,
#'   obs_ensemble = obs_ensemble,
#'   obs_target   = obs_target,
#'   weights      = weights,
#'   parcov_inv   = parcov_inv,
#'   cur_lam      = 1.0
#' )
#' dim(res$upgrade)
#' res$savings_pct
#' }
#' @export
surrogate_ensemble_update <- function(par_ensemble, obs_ensemble, obs_target, weights, parcov_inv, cur_lam = 1.0, uncertainty_threshold = 0.1, eigthresh = 1e-6) {
    .Call(`_PESTO_surrogate_ensemble_update`, par_ensemble, obs_ensemble, obs_target, weights, parcov_inv, cur_lam, uncertainty_threshold, eigthresh)
}

#' Adaptive Ensemble Sizing
#'
#' Dynamically determines the optimal ensemble size based on
#' convergence diagnostics and information-theoretic criteria.
#'
#' Uses the effective sample size (ESS) and coefficient of variation
#' of phi to determine whether the ensemble is too large (wasting
#' compute) or too small (poor UQ coverage).
#'
#' @param phi_values Numeric vector. Current phi values per realisation.
#' @param current_size Integer. Current ensemble size.
#' @param min_size Integer. Minimum ensemble size (default 20).
#' @param max_size Integer. Maximum ensemble size (default 500).
#' @param cv_target Numeric. Target coefficient of variation for phi (default 0.3).
#' @return A list with recommended_size, reasoning, and diagnostics.
#' @examples
#' set.seed(1L)
#' phi_values <- rnorm(50L, mean = 100, sd = 20)^2
#' res <- adaptive_ensemble_size(
#'   phi_values   = phi_values,
#'   current_size = 50L
#' )
#' res$recommended_size
#' res$cv_phi
#' res$ess_ratio
#' @export
adaptive_ensemble_size <- function(phi_values, current_size, min_size = 20L, max_size = 500L, cv_target = 0.3) {
    .Call(`_PESTO_adaptive_ensemble_size`, phi_values, current_size, min_size, max_size, cv_target)
}

#' Train a Sparse GP Surrogate via Random Fourier Features
#'
#' Approximates the RBF kernel GP using random Fourier features,
#' reducing training cost from O(n^3) to O(n * D^2) where D is
#' the number of random features (typically 100-500). This enables
#' GP surrogates for ensembles of 1,000+ realisations.
#'
#' The RBF kernel k(x,x') = sigma^2 exp(-||x-x'||^2 / 2l^2)
#' is approximated by k(x,x') ~ z(x)^T z(x') where
#' z(x) = sqrt(2/D) * cos(W*x + b), where W are random frequencies.
#' with w_j ~ N(0, I/l^2) and b_j ~ Uniform(0, 2*pi).
#'
#' @param X_train Matrix (n x npar). Training parameter sets.
#' @param Y_train Matrix (n x nobs). Corresponding model outputs.
#' @param n_features Integer. Number of random Fourier features (default 200).
#' @param length_scale Numeric. Kernel length scale (0 = median heuristic).
#' @param noise_var Numeric. Observation noise variance.
#' @return A list containing the trained RFF model.
#' @examples
#' set.seed(1L)
#' X_train <- matrix(rnorm(30 * 4), 30, 4)
#' Y_train <- matrix(rnorm(30 * 6), 30, 6)
#' rff <- train_rff_surrogate(X_train, Y_train, n_features = 100L)
#' rff$train_mse
#' X_new <- matrix(rnorm(5 * 4), 5, 4)
#' pred  <- predict_rff_surrogate(rff, X_new)
#' dim(pred$mean)
#' @export
train_rff_surrogate <- function(X_train, Y_train, n_features = 200L, length_scale = 0.0, noise_var = 1e-4) {
    .Call(`_PESTO_train_rff_surrogate`, X_train, Y_train, n_features, length_scale, noise_var)
}

#' Predict with RFF Sparse GP Surrogate
#'
#' @param rff A trained RFF model (from \code{train_rff_surrogate}).
#' @param X_new Matrix (m x npar). New parameter sets.
#' @return A list with mean predictions and approximate uncertainties.
#' @examples
#' set.seed(1L)
#' X_train <- matrix(rnorm(30 * 4), 30, 4)
#' Y_train <- matrix(rnorm(30 * 6), 30, 6)
#' rff     <- train_rff_surrogate(X_train, Y_train, n_features = 100L)
#' X_new   <- matrix(rnorm(5 * 4), 5, 4)
#' pred    <- predict_rff_surrogate(rff, X_new)
#' dim(pred$mean)
#' length(pred$uncertainty)
#' @export
predict_rff_surrogate <- function(rff, X_new) {
    .Call(`_PESTO_predict_rff_surrogate`, rff, X_new)
}

